name: Unittest Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest test_file.py